server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.96.171:8848

#消费者将要去访问的微服务名称
servoce-url:
  nacos-user-service: http://nacos-payment-provider